name: infrastructure

on: push

env:
  GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_BACKEND_CREDENTIALS }}

defaults:
  run:
    working-directory: ./terraform

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: hashicorp/setup-terraform@v3
        name: Install terraform v1.9.2
        with:
          terraform_version: "1.9.2"
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan
        continue-on-error: false
